name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#0f766e&color_dots=#e2e8f0,#cbd5e1,#94a3b8,#475569,#0f172a
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#f59e0b&color_dots=#0f172a,#1e293b,#334155,#64748b,#e2e8f0

      - name: push snake assets to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
